using System.ComponentModel;
using Microsoft.SemanticKernel;

namespace PDA.Services.LLM.KernelPlugins;

/// <summary>
/// Kernel Plugin: Dashboard and report generation
/// Creates HTML dashboards with charts, tables, and interactive elements
/// </summary>
public class DashboardPlugin
{
    /// <summary>
    /// Generate an HTML dashboard for data visualization.
    /// The HTML content is rendered in an expandable dashboard panel in the chat UI.
    /// </summary>
    [KernelFunction("createDashboard")]
    [Description("Create an HTML dashboard/report to visualize data. " +
                 "The dashboard supports Chart.js for charts, tables, multi-tab layouts, and filters. " +
                 "Use this when the user wants data visualizations, charts, summary reports, or interactive dashboards. " +
                 "The HTML will be rendered in an expandable dashboard panel in the UI.")]
    public string CreateDashboard(
        [Description("Dashboard title - displayed in the panel header")]
        string title,
        [Description("Optional dashboard description shown below the title")]
        string description = "",
        [Description("Full HTML content of the dashboard. Use Chart.js for charts (canvas element), " +
                     "tables with class 'neo-table' for data grids, div with class 'grid-2' for layouts. " +
                     "Include <script> tags for Chart.js initialization. " +
                     "Use a professional dark theme with accent colors.")]
        string htmlContent = "")
    {
        // Wrap the HTML content in a proper dashboard structure
        var wrapped = $"""
<div class="dashboard-container" style="font-family: 'Segoe UI', system-ui, sans-serif;">
    <div style="padding: 12px 0; border-bottom: 2px solid #2d3a4a; margin-bottom: 16px;">
        <h2 style="margin:0; color: #ff6b6b; font-size: 1.5em;">📊 {title}</h2>
        {(string.IsNullOrEmpty(description) ? "" : $"<p style='color:#b0b8c8; margin:4px 0 0 0;'>{description}</p>")}
    </div>
    {htmlContent}
    <div style="margin-top:16px; padding-top:12px; border-top:1px solid #2d3a4a; color:#6b7c93; font-size:11px;">
        Generated by PDA • {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC
    </div>
</div>
""";
        return wrapped;
    }
}
